### ISSUE TITLE
use library() rather than require()

### ISSUE THREAD

**Issue by djnavarro** [belinda-xie/birds_parameters#1]
I think what I'm going to do is use the issues threads to make suggestions and give explantions! Seems like the cleanest way :smiley_cat: 

First thought: As a general rule it's probably better to use `library()` here rather than `require()` in situations like this. If the package isn't present, `library()` will throw an error, whereas `require()` will silently do nothing. So if that package is actually needed and you used `require()` you're going to get an error anyway as soon as R tries to do something with that package, but it will be confusing to the user (i.e., future you!) because you'll be looking at the wrong line of code trying to find the bug.

https://github.com/belinda-xie/birds_parameters/blob/3fc6e8d5f15d81c7ae18065ba947fc6c82bfe2d0/modeling_expt1.R#L7

**Comment by belinda-xie** [comment]
Done! Thanks for the tip :) So useful to have these kinds of rules
