### ISSUE TITLE
rm() not advised (sort of...)

### ISSUE THREAD

**Issue by djnavarro** [belinda-xie/birds_parameters#2]
I have mixed feelings about this one:

https://github.com/belinda-xie/birds_parameters/blob/3fc6e8d5f15d81c7ae18065ba947fc6c82bfe2d0/modeling_expt1.R#L12

The usual advice is that it's better not to rely on `rm()` within a script to clean up the workspace. The idea here is that if you want to guarantee a clean environment you should restart R (e.g. from the RStudio menu) rather than "just" remove variables. Plus it might be the case that the future user actually has something in their environment that they need and it is a tiny bit impolite for your script to mess with their workspace. 

Offered only as comment. It's not something I have strong suggestions about!

**Comment by belinda-xie** [comment]
Ahh understood, bit presumptuous to ask others to clear their environment. Just found the Ctrl+Shift+F10 shortcut to restart R, so will use that in future!
