### ISSUE TITLE
alternative way to manage file paths 

### ISSUE THREAD

**Issue by djnavarro** [belinda-xie/birds_parameters#3]
This is really neat, and I've never seen this solution before. One possible downside to this might be that it requires RStudio (I think?)

https://github.com/belinda-xie/birds_parameters/blob/3fc6e8d5f15d81c7ae18065ba947fc6c82bfe2d0/modeling_expt1.R#L13

The solution I've seen people usually employ is to use the `here` package. For that to work, you need to *either* be working within an RStudio project (so there should be a `birds_parameters.RProj` file in the project folder, *or* there should be an empty text file in the project folder called `.here`. The `here()` function in the here package allows you to specify paths relative to the location of that project file. So instead of setting the working directory with `setwd()` you can delete line 13, and replace the current line 15

https://github.com/belinda-xie/birds_parameters/blob/3fc6e8d5f15d81c7ae18065ba947fc6c82bfe2d0/modeling_expt1.R#L15

with this 

```
library(here) # <- earlier in the script
source(here("BayesGen-BX.R"))
```
Note that later on you'll have to modify the "write" commands such as this one too:

https://github.com/belinda-xie/birds_parameters/blob/3fc6e8d5f15d81c7ae18065ba947fc6c82bfe2d0/modeling_expt1.R#L198

Given that this project is essentially complete and the code works fine as it is, I wouldn't bother changing it for this project, just something you might think about doing differently for the next one! :grinning:

**Comment by belinda-xie** [comment]
Noted :) thanks again for the tip, I don't often spend the time trying to improve my code, so it's super useful to read these comments.
