### ISSUE TITLE
add a README.md file, you'll be happy you did!

### ISSUE THREAD

**Issue by djnavarro** [belinda-xie/birds_parameters#4]
The readme file is sooooo helpful to you several months/years later trying to remember what the heck you are looking at in your own repository. Even something as minimal as this one will buy you a lot:

https://github.com/djnavarro/shepard-theory/blob/master/README.md

**Comment by djnavarro** [comment]
One reason you might want to do it in this case is to remind "future you" which scripts do what. There is one helper script (`BayesGen-BX.R`) and three separate simulations scripts, one for each experiment. That much is easy to figure out. But when I looked at the repository initially I couldn't work out which of the simulation scripts was creating which of the csv files. It's not intuitive from the beginning that `typesMed3.csv` would be associated with experiment 1. The most "elegant" way to do this is to have the files named and the folders structured in a way that makes it obvious, but you can also solve the same problem by just explaining it in the README

**Comment by belinda-xie** [comment]
Resolved by copying much of your README file. Will start with one of these next time!
